# Generated by Django 4.0.6 on 2022-07-20 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=254, verbose_name='City')),
                ('address_one', models.CharField(max_length=254, verbose_name='address 1')),
                ('address_two', models.CharField(max_length=254, verbose_name='address 2')),
                ('primary_phone', models.CharField(max_length=254, verbose_name='primary phone number')),
                ('secondary_phone', models.CharField(max_length=254, verbose_name='secondary phone number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
