# Generated by Django 4.0.6 on 2022-07-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='App Users',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='User Addresses',
        ),
    ]
