# Generated by Django 4.0.6 on 2022-07-21 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=254, verbose_name='city of residence')),
                ('address_one', models.CharField(max_length=254, verbose_name='address 1')),
                ('phone_one', models.CharField(max_length=254, verbose_name='primary phone')),
                ('phone_two', models.CharField(max_length=254, verbose_name='secondary phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User Addresses',
            },
        ),
    ]
