# Generated by Django 4.0.6 on 2022-07-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_one',
            new_name='address',
        ),
    ]
