# Generated by Django 4.0.6 on 2022-07-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_address_one_address_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
