# Generated by Django 4.0.6 on 2022-07-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_newslettersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_date']},
        ),
    ]
