# Generated by Django 4.0.6 on 2022-08-08 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newslettersubscription_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='user',
        ),
    ]
