# Generated by Django 4.0.6 on 2022-08-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_newslettersubscription_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User Accounts',
        ),
    ]
