# Generated by Django 4.0.6 on 2022-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(max_length=254, verbose_name='delivery method')),
                ('shipping_cost', models.IntegerField(default=0, verbose_name='shipping cost')),
                ('requires_payment', models.BooleanField(default=True, verbose_name='payment needed')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Shipping Cost',
                'ordering': ['-created_date'],
            },
        ),
    ]
