# Generated by Django 4.0.6 on 2022-08-12 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uic', models.CharField(max_length=254, verbose_name='unique ID code')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=254, verbose_name='first name')),
                ('last_name', models.CharField(max_length=254, verbose_name='last name')),
                ('address', models.CharField(max_length=254, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=254, null=True, verbose_name='address two')),
                ('postal_code', models.CharField(blank=True, max_length=254, null=True, verbose_name='postal code')),
                ('phone_number', models.CharField(max_length=254, verbose_name='phone number')),
                ('city', models.CharField(max_length=254, verbose_name='city')),
                ('place', models.CharField(max_length=254, verbose_name='place of residence')),
                ('delivery_method', models.CharField(max_length=254, verbose_name='delivery method')),
                ('paid', models.BooleanField(default=False, verbose_name='has been paid?')),
                ('paid_amount', models.FloatField(default=0, verbose_name='total payable')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('picked', 'Picked')], default='ordered', max_length=254, verbose_name='order status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orders Table',
                'ordering': ['-created_date'],
            },
        ),
    ]
