# Generated by Django 4.0.6 on 2022-07-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='has been shipping'),
        ),
    ]
