# Generated by Django 4.0.6 on 2022-07-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipped'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date']},
        ),
    ]
