# Generated by Django 4.0.6 on 2022-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=254, verbose_name='city of residence'),
        ),
    ]
