# Generated by Django 4.0.6 on 2022-08-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shippingcost',
            table='Shipping Costs',
        ),
    ]
