# Generated by Django 4.0.6 on 2022-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliveryorder_pickuporder_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved for shipping (paid)'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved for shipping (paid)'),
        ),
    ]
