# Generated by Django 4.0.6 on 2022-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_deliveryorder_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved for shipping (Paid)'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='fulfilled',
            field=models.BooleanField(default=False, verbose_name='has been fulfilled (Delivered)'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved for shipping (Paid)'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='fulfilled',
            field=models.BooleanField(default=False, verbose_name='has been fulfilled (Delivered)'),
        ),
    ]
