# Generated by Django 4.0.6 on 2022-07-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_deliveryorder_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryorder',
            old_name='phone_one',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='phone_one',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='phone_two',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='phone_two',
        ),
    ]
