# Generated by Django 4.0.6 on 2022-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_deliveryorder_item_alter_pickuporder_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='item',
            field=models.ManyToManyField(to='orders.cartitem'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='item',
            field=models.ManyToManyField(to='orders.cartitem'),
        ),
    ]
