# Generated by Django 4.0.6 on 2022-08-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_shippingcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcost',
            name='shipping_cost',
            field=models.IntegerField(default=0, verbose_name='shipping cost'),
        ),
    ]
