# Generated by Django 4.0.6 on 2022-08-06 12:02

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254, unique=True, verbose_name='product name')),
                ('full_name', models.CharField(max_length=254, verbose_name='product full name')),
                ('slug', models.SlugField(max_length=254, verbose_name='product slug')),
                ('price', models.FloatField(default=0, verbose_name='product price')),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='thumbnail')),
                ('description', models.TextField(verbose_name='describe the product')),
                ('specifications', models.TextField(verbose_name='specifications of the product')),
                ('slide_one', cloudinary.models.CloudinaryField(max_length=255, verbose_name='slide_one')),
                ('slide_two', cloudinary.models.CloudinaryField(max_length=255, verbose_name='slide_two')),
                ('slide_three', cloudinary.models.CloudinaryField(max_length=255, verbose_name='slide_three')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products Table',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=254, verbose_name='category name')),
                ('slug', models.SlugField(max_length=254, verbose_name='category slug')),
                ('description', models.TextField(verbose_name='describe the category')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products Category',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=254, verbose_name='tag name')),
                ('slug', models.SlugField(max_length=254, verbose_name='tag slug')),
                ('description', models.TextField(verbose_name='describe the tag')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Product Tags',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=254, verbose_name='item name')),
                ('rating', models.IntegerField(default=0, verbose_name='item rating')),
                ('review', models.TextField(verbose_name='item review')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Products Reviews',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity of product')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'Products Inventory',
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_review',
            field=models.ManyToManyField(to='products.productreview'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(to='products.producttag'),
        ),
    ]
