# Generated by Django 4.0.6 on 2022-07-25 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='product name')),
                ('slug', models.SlugField(max_length=254, verbose_name='product slug')),
                ('price', models.IntegerField(default=0, verbose_name='product price')),
                ('thumbnail', models.URLField(max_length=254, verbose_name='product thumbnail')),
                ('description', models.TextField(verbose_name='describe the product')),
                ('specifications', models.TextField(verbose_name='specifications of the product')),
                ('slide_one', models.URLField(max_length=254, verbose_name='product slide 1')),
                ('slide_two', models.URLField(max_length=254, verbose_name='product slide 2')),
                ('slide_three', models.URLField(max_length=254, verbose_name='product slide 3')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products Table',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='category name')),
                ('slug', models.SlugField(max_length=254, verbose_name='category slug')),
                ('description', models.TextField(verbose_name='describe the category')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products Category',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='item name')),
                ('rating', models.IntegerField(default=0, verbose_name='item rating')),
                ('review', models.TextField(verbose_name='item review')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Products Reviews',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity of product')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'Products Inventory',
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_review',
            field=models.ManyToManyField(to='products.productreview'),
        ),
    ]
