# Generated by Django 4.0.6 on 2022-07-25 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='item name')),
                ('rating', models.IntegerField(default=0, verbose_name='item rating')),
                ('review', models.TextField(verbose_name='item review')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products Reviews',
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='specifications of the product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_review',
            field=models.ManyToManyField(to='products.productreview'),
        ),
    ]
