# Generated by Django 4.0.6 on 2022-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(verbose_name='category description'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='product quantity'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='description',
            field=models.TextField(verbose_name='tag description'),
        ),
    ]
