# Generated by Django 4.0.6 on 2022-08-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productreview_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productbrand',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='name',
            new_name='item_name',
        ),
    ]
